//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.20 at 11:55:08 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://earth.google.com/kml/2.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.google.earth.kml._2;
